import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export type CandidateStatus = 'draft' | 'in_process' | 'offer_sent' | 'offer_accepted' | 'offer_rejected' | 'archived';

export interface Candidate {
  id: string;
  candidate_code: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string | null;
  nationality: string | null;
  work_location_id: string | null;
  department_id: string | null;
  position_id: string | null;
  manager_employee_id: string | null;
  proposed_start_date: string | null;
  notes: string | null;
  status: CandidateStatus;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  // Joined data
  work_location?: { id: string; name: string } | null;
  department?: { id: string; name: string } | null;
  position?: { id: string; title: string } | null;
  manager?: { id: string; first_name: string; last_name: string } | null;
}

export interface CandidateFormData {
  first_name: string;
  last_name: string;
  email: string;
  phone?: string;
  nationality?: string;
  work_location_id?: string;
  department_id?: string;
  position_id?: string;
  manager_employee_id?: string;
  proposed_start_date?: string;
  notes?: string;
  status?: CandidateStatus;
}

interface CandidateFilters {
  status?: CandidateStatus | 'all';
  department_id?: string;
  work_location_id?: string;
  search?: string;
}

export function useCandidates(filters?: CandidateFilters) {
  return useQuery({
    queryKey: ["candidates", filters],
    queryFn: async () => {
      let query = supabase
        .from("candidates")
        .select(`
          *,
          work_location:work_locations(id, name),
          department:departments(id, name),
          position:positions(id, title),
          manager:employees!candidates_manager_employee_id_fkey(id, first_name, last_name)
        `)
        .order("created_at", { ascending: false });

      if (filters?.status && filters.status !== 'all') {
        query = query.eq("status", filters.status);
      }
      if (filters?.department_id) {
        query = query.eq("department_id", filters.department_id);
      }
      if (filters?.work_location_id) {
        query = query.eq("work_location_id", filters.work_location_id);
      }
      if (filters?.search) {
        query = query.or(`first_name.ilike.%${filters.search}%,last_name.ilike.%${filters.search}%,email.ilike.%${filters.search}%,candidate_code.ilike.%${filters.search}%`);
      }

      const { data, error } = await query;

      if (error) throw error;
      return data as Candidate[];
    },
  });
}

export function useCandidate(id: string | undefined) {
  return useQuery({
    queryKey: ["candidate", id],
    queryFn: async () => {
      if (!id) return null;
      
      const { data, error } = await supabase
        .from("candidates")
        .select(`
          *,
          work_location:work_locations(id, name),
          department:departments(id, name),
          position:positions(id, title),
          manager:employees!candidates_manager_employee_id_fkey(id, first_name, last_name)
        `)
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as Candidate;
    },
    enabled: !!id,
  });
}

export function useCreateCandidate() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: CandidateFormData) => {
      const { data: result, error } = await supabase
        .from("candidates")
        .insert({
          ...data,
          candidate_code: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["candidates"] });
      toast.success("Candidate created successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to create candidate: ${error.message}`);
    },
  });
}

export function useUpdateCandidate() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: Partial<CandidateFormData> }) => {
      const { data: result, error } = await supabase
        .from("candidates")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return result;
    },
    onSuccess: (_, { id }) => {
      queryClient.invalidateQueries({ queryKey: ["candidates"] });
      queryClient.invalidateQueries({ queryKey: ["candidate", id] });
      toast.success("Candidate updated successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to update candidate: ${error.message}`);
    },
  });
}

export function useArchiveCandidate() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("candidates")
        .update({ status: 'archived' as CandidateStatus })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["candidates"] });
      toast.success("Candidate archived");
    },
    onError: (error: Error) => {
      toast.error(`Failed to archive candidate: ${error.message}`);
    },
  });
}

export function useDeleteCandidate() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("candidates")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["candidates"] });
      toast.success("Candidate deleted successfully");
    },
    onError: (error: Error) => {
      toast.error(`Failed to delete candidate: ${error.message}`);
    },
  });
}
